/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.pdfjet.*;
import controller.Kontroler;
import controller.Podaci;
import domen.Liga;
import domen.Mec;
import domen.Takmicar;
import domen.Takmicenje;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import konstante.Konstante;
import table_models.TableModelLige;
import table_models.TableModelTakmicari;
import table_models.TableModelTakmicariZaLigu;
import table_models.TableModelTakmicenje;
import transfer.KlijentTransferObjekat;
import util.CustomComparator;
import view.pdf.DflPDF;
import view.tabLige.DlgUnosLige;
import view.tabMecevi.DlgListaSvihMecevaLige;
import view.tabMecevi.DlgUnesiMec;
import view.tabTakmicar.DlgIzmenaTakmicara;
import view.tabTakmicar.DlgUnosTakmicara;
import view.tabTakmicenja.DlgIzmeniTakmicenje;
import view.tabTakmicenja.DlgUnosTakmicenja;
import view.tabTakmicenja.DlgUnosTipaTakmicenja;

/**
 *
 * @author Raca420
 */
public class frmGlavna extends javax.swing.JFrame {
    
    private static List<Takmicenje> lista = new ArrayList<>();
    private static Liga liga_trenutna_tabTakmicari;
    private static Liga liga_trenutna_tabMecevi;
    
    public static Takmicar takmicarZaUpdate;
    private static Takmicar takmicarZaDelete;
    
    public static void napuniListuTakmicenja() {
        lista = Podaci.listaTakmicenja;
        TableModelTakmicenje tm = new TableModelTakmicenje(lista);
        tblTakmicenja.setModel(tm);
        cbxTakmicenjaTAK.setModel(new DefaultComboBoxModel(lista.toArray()));

        // ZA TAB MECEVI //
        cbxTakmicenje_mec.setModel(new DefaultComboBoxModel(lista.toArray()));
        
    }
    
    public static Liga getLiga_trenutna_tabTakmicari() {
        return liga_trenutna_tabTakmicari;
    }
    
    public static Takmicar getT1() {
        return takmicarZaUpdate;
    }
    
    public static Liga getLiga_trenutna_tabMecevi() {
        return liga_trenutna_tabMecevi;
    }
    
    public static Takmicar getTakmicarZaDelete() {
        return takmicarZaDelete;
    }

    /**
     * Creates new form frmGlavna
     */
    public frmGlavna() {
        initComponents();
        this.getContentPane().setBackground(Design.BOJA_POZADINE);
        pnlTabTakmicenje.setBackground(Design.BOJA_POZADINE);
        pnlTabLiga.setBackground(Design.BOJA_POZADINE);
        pnlTabTakmicari.setBackground(Design.BOJA_POZADINE);
        pnlTabMecevi.setBackground(Design.BOJA_POZADINE);
        refreshTabelu();
        srediPretragu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlTabTakmicenje = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTakmicenja = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnIzmeniTakm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlTabLiga = new javax.swing.JPanel();
        btnUnosLige = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLigeSve = new javax.swing.JTable();
        pnlTabTakmicari = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTakmicari = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cbxTakmicenjaTAK = new javax.swing.JComboBox();
        cbxLigaTAK = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIzmenaTakmicara = new javax.swing.JButton();
        btnObrisiTakmicara = new javax.swing.JButton();
        jtfPretraga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlTabMecevi = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblTakmicariTeLige = new javax.swing.JTable();
        cbxTakmicenje_mec = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxLiga_mec = new javax.swing.JComboBox();
        btnUnesiMecZaLigu = new javax.swing.JButton();
        lblTakmicariLiga = new javax.swing.JLabel();
        btnListaMeceva = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni prozor");

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyReleased(evt);
            }
        });

        pnlTabTakmicenje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlTabTakmicenjeKeyPressed(evt);
            }
        });

        tblTakmicenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTakmicenja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTakmicenjaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTakmicenja);

        jButton1.setBackground(Design.BOJA_BUTTON);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Unos takmičenja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(Design.BOJA_BUTTON);
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Unos tipa takmičenja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnIzmeniTakm.setBackground(Design.BOJA_BUTTON);
        btnIzmeniTakm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIzmeniTakm.setText("Izmeni takmičenje");
        btnIzmeniTakm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniTakmActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista svih takmicenja:");

        javax.swing.GroupLayout pnlTabTakmicenjeLayout = new javax.swing.GroupLayout(pnlTabTakmicenje);
        pnlTabTakmicenje.setLayout(pnlTabTakmicenjeLayout);
        pnlTabTakmicenjeLayout.setHorizontalGroup(
            pnlTabTakmicenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabTakmicenjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabTakmicenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeniTakm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTabTakmicenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 262, Short.MAX_VALUE))
        );
        pnlTabTakmicenjeLayout.setVerticalGroup(
            pnlTabTakmicenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabTakmicenjeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(pnlTabTakmicenjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTabTakmicenjeLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeniTakm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rad sa takmičenjima", pnlTabTakmicenje);

        pnlTabLiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnlTabLigaKeyPressed(evt);
            }
        });

        btnUnosLige.setBackground(Design.BOJA_BUTTON);
        btnUnosLige.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUnosLige.setText("Unos lige");
        btnUnosLige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosLigeActionPerformed(evt);
            }
        });

        tblLigeSve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblLigeSve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLigeSveMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblLigeSve);

        javax.swing.GroupLayout pnlTabLigaLayout = new javax.swing.GroupLayout(pnlTabLiga);
        pnlTabLiga.setLayout(pnlTabLigaLayout);
        pnlTabLigaLayout.setHorizontalGroup(
            pnlTabLigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLigaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabLigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnosLige, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        pnlTabLigaLayout.setVerticalGroup(
            pnlTabLigaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabLigaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUnosLige, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rad sa ligama", pnlTabLiga);

        tblTakmicari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTakmicari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTakmicariMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTakmicari);

        jButton3.setBackground(Design.BOJA_BUTTON);
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Unos takmičara");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(Design.BOJA_BUTTON);
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Unos tipa takmičenja");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cbxTakmicenjaTAK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTakmicenjaTAKItemStateChanged(evt);
            }
        });

        cbxLigaTAK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLigaTAKItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Izaberite ligu:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Izaberite takmicenje:");

        btnIzmenaTakmicara.setBackground(Design.BOJA_BUTTON);
        btnIzmenaTakmicara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIzmenaTakmicara.setText("Izmena takmičara");
        btnIzmenaTakmicara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaTakmicaraActionPerformed(evt);
            }
        });

        btnObrisiTakmicara.setBackground(Design.BOJA_BUTTON);
        btnObrisiTakmicara.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnObrisiTakmicara.setText("Obrisi takmičara");
        btnObrisiTakmicara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiTakmicaraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pretrazi takmicare:");

        javax.swing.GroupLayout pnlTabTakmicariLayout = new javax.swing.GroupLayout(pnlTabTakmicari);
        pnlTabTakmicari.setLayout(pnlTabTakmicariLayout);
        pnlTabTakmicariLayout.setHorizontalGroup(
            pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabTakmicariLayout.createSequentialGroup()
                .addGroup(pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabTakmicariLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(544, 544, 544))
                    .addGroup(pnlTabTakmicariLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmenaTakmicara, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTakmicenjaTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxLigaTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisiTakmicara, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(266, 266, 266))
            .addGroup(pnlTabTakmicariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTabTakmicariLayout.setVerticalGroup(
            pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabTakmicariLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabTakmicariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabTakmicariLayout.createSequentialGroup()
                        .addComponent(cbxTakmicenjaTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxLigaTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmenaTakmicara, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisiTakmicara, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rad sa takmičarima", pnlTabTakmicari);

        tblTakmicariTeLige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblTakmicariTeLige);

        cbxTakmicenje_mec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTakmicenje_mecItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Izaberite takmicenje:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Izaberite ligu:");

        cbxLiga_mec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLiga_mecItemStateChanged(evt);
            }
        });

        btnUnesiMecZaLigu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUnesiMecZaLigu.setText("Unesite mec za ovu ligu");
        btnUnesiMecZaLigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiMecZaLiguActionPerformed(evt);
            }
        });

        lblTakmicariLiga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnListaMeceva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnListaMeceva.setText("Lista meceva");
        btnListaMeceva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaMecevaActionPerformed(evt);
            }
        });

        btnPDF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPDF.setText("Odstampaj u pdf");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabMeceviLayout = new javax.swing.GroupLayout(pnlTabMecevi);
        pnlTabMecevi.setLayout(pnlTabMeceviLayout);
        pnlTabMeceviLayout.setHorizontalGroup(
            pnlTabMeceviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMeceviLayout.createSequentialGroup()
                .addGroup(pnlTabMeceviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabMeceviLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTabMeceviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxLiga_mec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTakmicenje_mec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUnesiMecZaLigu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListaMeceva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTabMeceviLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(lblTakmicariLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        pnlTabMeceviLayout.setVerticalGroup(
            pnlTabMeceviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabMeceviLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTakmicariLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabMeceviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTabMeceviLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTakmicenje_mec, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxLiga_mec, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUnesiMecZaLigu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListaMeceva, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rad sa mečevima", pnlTabMecevi);

        jScrollPane1.setViewportView(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(946, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DlgUnosTakmicenja(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new DlgUnosTipaTakmicenja(this, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyReleased

    }//GEN-LAST:event_jTabbedPane1KeyReleased

    private void pnlTabTakmicenjeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlTabTakmicenjeKeyPressed

    }//GEN-LAST:event_pnlTabTakmicenjeKeyPressed

    private void tblTakmicenjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTakmicenjaMouseClicked
//        if (evt.getClickCount() == 2) {
//            JTable target = (JTable) evt.getSource();
//            int row = target.getSelectedRow();
//            Takmicenje t = target.getSelectedRow
//        }
    }//GEN-LAST:event_tblTakmicenjaMouseClicked

    private void btnIzmeniTakmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniTakmActionPerformed
        if (tblTakmicenja.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selektujte takmicenje");
            return;
        }
        Takmicenje t;
        t = lista.get(tblTakmicenja.convertRowIndexToModel(tblTakmicenja.getSelectedRow()));
        DlgIzmeniTakmicenje dlg = new DlgIzmeniTakmicenje(null, true);
        dlg.napuniView(t);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnIzmeniTakmActionPerformed

    private void btnUnosLigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosLigeActionPerformed
        Kontroler.getInstance().posaljiZahtevZaPodatke();
        new DlgUnosLige(this, true).setVisible(true);
    }//GEN-LAST:event_btnUnosLigeActionPerformed

    private void tblLigeSveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLigeSveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLigeSveMouseClicked

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed

    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void pnlTabLigaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlTabLigaKeyPressed
        System.out.println("adsnij");
    }//GEN-LAST:event_pnlTabLigaKeyPressed

    private void tblTakmicariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTakmicariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTakmicariMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (cbxLigaTAK.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali ligu");
        } else {
            new DlgUnosTakmicara(this, true).setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbxTakmicenjaTAKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTakmicenjaTAKItemStateChanged
        if (evt.getStateChange() == 1) {
            Takmicenje t = (Takmicenje) cbxTakmicenjaTAK.getSelectedItem();
            List<Liga> ls = new ArrayList<>();
            for (Liga l : Podaci.listaLiga) {
                if (l.getTakmicenje().getTakmicenjeID() == t.getTakmicenjeID()) {
                    ls.add(l);
                }
            }
            cbxLigaTAK.setModel(new DefaultComboBoxModel(ls.toArray()));
            if (cbxLigaTAK.getItemCount() > 0) {
                cbxLigaTAK.setSelectedIndex(0);
                liga_trenutna_tabTakmicari = (Liga) cbxLigaTAK.getSelectedItem();
            }
        }
    }//GEN-LAST:event_cbxTakmicenjaTAKItemStateChanged

    private void cbxLigaTAKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLigaTAKItemStateChanged
//        Kontroler.getInstance().posaljiZahtevZaPodatke()
        if (evt.getStateChange() == 1) {
            liga_trenutna_tabTakmicari = (Liga) cbxLigaTAK.getSelectedItem();
        }
    }//GEN-LAST:event_cbxLigaTAKItemStateChanged

    private void btnIzmenaTakmicaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaTakmicaraActionPerformed
        if (tblTakmicari.getSelectedRowCount() == 1) {
            
            takmicarZaUpdate = Podaci.listaTakmicara.get(tblTakmicari.getSelectedRow());
            System.out.println("###" + takmicarZaUpdate.getTakmicarID());
            DlgIzmenaTakmicara dl = new DlgIzmenaTakmicara(this, true);
            dl.setVisible(true);
        }

    }//GEN-LAST:event_btnIzmenaTakmicaraActionPerformed

    private void cbxTakmicenje_mecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTakmicenje_mecItemStateChanged
        if (evt.getStateChange() == 1) {
            Takmicenje t = (Takmicenje) cbxTakmicenje_mec.getSelectedItem();
            List<Liga> ls = new ArrayList<>();
            for (Liga l : Podaci.listaLiga) {
                if (l.getTakmicenje().getTakmicenjeID() == t.getTakmicenjeID()) {
                    ls.add(l);
                }
            }
            cbxLiga_mec.setModel(new DefaultComboBoxModel(ls.toArray()));
            if (cbxLiga_mec.getItemCount() > 0) {
                cbxLiga_mec.setSelectedIndex(0);
                liga_trenutna_tabMecevi = (Liga) cbxLiga_mec.getSelectedItem();
                napuniTabeluTakmicaraLige();
            }
        }
    }//GEN-LAST:event_cbxTakmicenje_mecItemStateChanged

    private void cbxLiga_mecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLiga_mecItemStateChanged
        if (evt.getStateChange() == 1) {
            liga_trenutna_tabMecevi = (Liga) cbxLiga_mec.getSelectedItem();
            napuniTabeluTakmicaraLige();
        }
    }//GEN-LAST:event_cbxLiga_mecItemStateChanged

    private void btnUnesiMecZaLiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiMecZaLiguActionPerformed
        if (cbxLiga_mec.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali ligu");
        } else {
            new DlgUnesiMec(this, true).setVisible(true);
        }
    }//GEN-LAST:event_btnUnesiMecZaLiguActionPerformed

    private void btnObrisiTakmicaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiTakmicaraActionPerformed
        if (tblTakmicari.getSelectedRowCount() == 1) {
            takmicarZaDelete = Podaci.listaTakmicara.get(tblTakmicari.getSelectedRow());
            
            KlijentTransferObjekat kto = new KlijentTransferObjekat();
            kto.setObjekat(takmicarZaDelete);
            kto.setOperacija(Konstante.OPERACIJA_DELETE_TAKMICARA);
            
            try {
                Kontroler.getInstance().posaljiObjekat(kto);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            refreshTabelu();
            napuniTblTakmicare();
        }
    }//GEN-LAST:event_btnObrisiTakmicaraActionPerformed

    private void btnListaMecevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaMecevaActionPerformed
        Kontroler.getInstance().posaljiZahtevZaPodatke();
        System.out.println("88" + liga_trenutna_tabMecevi.toString());
        
        DlgListaSvihMecevaLige dlg = new DlgListaSvihMecevaLige(this, true);
        List<Mec> listaMecevaLige = new ArrayList<>();
        for (Mec m : Podaci.listaMeceva) {
            System.out.println("99" + m.getTakmicarDID().getLiga().toString());
            if (m.getTakmicarDID().getLiga().equals(liga_trenutna_tabMecevi)) {
                listaMecevaLige.add(m);
            }
        }
        dlg.setModel(listaMecevaLige);
        System.out.println("999" + listaMecevaLige.toString());
        dlg.setVisible(true);
    }//GEN-LAST:event_btnListaMecevaActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        if (liga_trenutna_tabMecevi == null) {
            JOptionPane.showMessageDialog(this, "Nije izabrana liga", "GRESKA", JOptionPane.ERROR_MESSAGE);
        } else {
            
            new DflPDF(this, true).setVisible(true);
        }
        

    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGlavna().setVisible(true);
            }
        });
    }
    
    public static void napuniLige() {
        List<Liga> l = Podaci.listaLiga;
        tblLigeSve.setModel(new TableModelLige(l));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmenaTakmicara;
    private javax.swing.JButton btnIzmeniTakm;
    private javax.swing.JButton btnListaMeceva;
    private javax.swing.JButton btnObrisiTakmicara;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnUnesiMecZaLigu;
    private javax.swing.JButton btnUnosLige;
    public static javax.swing.JComboBox cbxLigaTAK;
    protected static javax.swing.JComboBox cbxLiga_mec;
    public static javax.swing.JComboBox cbxTakmicenjaTAK;
    protected static javax.swing.JComboBox cbxTakmicenje_mec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField jtfPretraga;
    private javax.swing.JLabel lblTakmicariLiga;
    private javax.swing.JPanel pnlTabLiga;
    private javax.swing.JPanel pnlTabMecevi;
    private javax.swing.JPanel pnlTabTakmicari;
    private javax.swing.JPanel pnlTabTakmicenje;
    public static javax.swing.JTable tblLigeSve;
    public static javax.swing.JTable tblTakmicari;
    public static javax.swing.JTable tblTakmicariTeLige;
    public static javax.swing.JTable tblTakmicenja;
    // End of variables declaration//GEN-END:variables

    public static void refreshTabelu() {
        Kontroler.getInstance().posaljiZahtevZaPodatke();
        
    }
    
    public static void napuniTblTakmicare() {
        tblTakmicari.setModel(new TableModelTakmicari(Podaci.listaTakmicara));
    }
    
    private void napuniTabeluTakmicaraLige() {
        
        if (liga_trenutna_tabMecevi != null) {
            List<Takmicar> pomLista = new ArrayList<>();
            for (Takmicar tak : Podaci.listaTakmicara) {
                if (tak.getLiga().getLigaID() == liga_trenutna_tabMecevi.getLigaID()) {
                    pomLista.add(tak);
                }
            }
            if (!pomLista.isEmpty()) {
                pomLista.sort(new CustomComparator());
                DflPDF.setPomLista(pomLista);
                tblTakmicariTeLige.setModel(new TableModelTakmicariZaLigu(pomLista));
            }
        }
    }
    
    private void srediPretragu() {
        jtfPretraga.getDocument().addDocumentListener(new DocumentListener() {
            
            @Override
            public void insertUpdate(DocumentEvent e) {
                ((TableModelTakmicari) tblTakmicari.getModel()).skloniSaListe(jtfPretraga.getText());
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                ((TableModelTakmicari) tblTakmicari.getModel()).vratiNaListu(jtfPretraga.getText());
            }
            
            @Override
            public void changedUpdate(DocumentEvent e) {
                JOptionPane.showMessageDialog(null, "nesto se desilo!");
            }
            
        });
    }
    
}
